# Generated by Django 3.2.12 on 2022-07-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='city',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='phone',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='state',
            new_name='bankbranch',
        ),
    ]
