# Generated by Django 3.2.12 on 2022-07-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20220707_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='place',
        ),
    ]
